### ISSUE TITLE
Please upgrade dependency on "ffi" to 2.0.x

### ISSUE THREAD

**Issue by eximius313** [pezi/dart_periphery#15]
FFI is [currently](https://pub.dev/packages/ffi) in version 2.0.1, while `dart_periphery` [depends on 1.1.2](https://github.com/pezi/dart_periphery/blob/main/pubspec.yaml), which prevents users from using other libraries.
Could you please upgrade `ffi` to `2.0.x`?

**Comment by pezi** [comment]
Update v0.9.2 wtih FFI 2.0.1 ist available
https://pub.dev/packages/dart_periphery

**Comment by eximius313** [comment]
awesome! thank you!
there is only one problem... you've upgraded also `path` to `1.8.2` while the nevest version of `flutter_test` supports only `1.8.1` :(

**Comment by pezi** [comment]
New corrected version is online.

**Comment by eximius313** [comment]
Thank you!
