### ISSUE TITLE
I2C send word error

### ISSUE THREAD

**Issue by frikadelki** [pezi/dart_periphery#25]
This is a neat library. Big thanks for developing it! Hope to see it get back to active life some day.

I think there is an issue when sending words via i2c.
Functions writeWord/writeWordReg
https://github.com/pezi/dart_periphery/blob/d994099d99f7a4d9d22ecfe89e4b9cf2576d8f5e/lib/src/i2c.dart#L393
https://github.com/pezi/dart_periphery/blob/d994099d99f7a4d9d22ecfe89e4b9cf2576d8f5e/lib/src/i2c.dart#L410
use the following code to split bytes and send them separately.
`array = [wordValue | 0xff, wordValue >> 8];`
The high byte gets sent ok, however the low byte gets OR'ed with 0xff, so 0xff always gets sent.
I believe it should be `& 0xff`.

**Comment by pezi** [comment]
Your issue was auto-closed by referencing this problem in the commit. Thanks for your help!
