### ISSUE TITLE
Rename Futter to Flutter

### ISSUE THREAD

**Issue by AlbanDurrheimer** [pezi/dart_periphery#7]
Hello,

I just noticed an error in several names:

- `isFutterPiEnv` => `isFlutterPiEnv`
- `_isFutterPi` => `_isFlutterPi`
- in the [readme#L476](https://github.com/pezi/dart_periphery/blob/66ed7e328e9f85bbda99d79e40a472750b83800d/README.md?plain=1#L476)

**Comment by pezi** [comment]
Thanks for your contribution!
